OK_FORMAT = True
test = {   'name': 'q23',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> # Your answer should be a number;\n>>> type(mark_hurd_pay) != str\nTrue', 'hidden': False, 'locked': False,
                                    "failure_message":""""The data type for ``mark_hurd_pay`` is incorrect. Ensure that your answer isn't a string value."""},
                                   {'code': ">>> # Don't forget to give your answer in dollars, not millions of;\n>>> # Dollars! ;\n>>> mark_hurd_pay != 5325\nTrue",
                                     'hidden': False, 'locked': False,
                                     "failure_message":""""The provided answer for ``mark_hurd_pay`` is incorrect. Ensure that your answer in dollars, not millions."""},
                                   {   'code': ">>> # Don't forget to give your answer in dollars, not millions of;\n>>> # Dollars!;\n>>> mark_hurd_pay == 53250000\nTrue",
                                       'hidden': False,
                                       'locked': False,
                                       "failure_message":""""The provided answer for ``mark_hurd_pay`` is incorrect. Ensure that your answer in dollars, not millions.""",
                                        "success_message":"""All answers provided are correct!"""}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
