OK_FORMAT = True
test = {   'name': 'q31',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> len(some_functions)==3\nTrue', 'hidden': False, 'locked': False,
                                    "failure_message":"""Incorrect! ``some_functions`` mustg only contain three elements!""",},
                                   {'code': '>>> # The first thing in your array may not be a function.;\n>>> callable(some_functions.item(0))\nTrue',
                                     'hidden': False, 'locked': False,
                                     "failure_message":"""Incorrect! The first element in your array may not be a function."""},
                                   {'code': '>>> # The second thing in your array may not be a function.;\n>>> callable(some_functions.item(1))\nTrue',
                                     'hidden': False, 'locked': False,
                                     "failure_message":"""Incorrect! The second element in your array may not be a function."""},
                                   {'code': '>>> # The third thing in your array may not be a function.;\n>>> callable(some_functions.item(2))\nTrue', 
                                    'hidden': False, 'locked': False,
                                    "failure_message":"""Incorrect! The third element in your array may not be a function.""",
                                    "success_message":"""All answers provided are correct!"""}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
