OK_FORMAT = True
test = {   'name': 'q3_4',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> isinstance(postban_rates, Table)\nTrue', 'hidden': False, 'locked': False,
                                    "failure_message":"""Incorrect: Expected `postban_rates` to be a table. Check the instructions again."""},
                                   {'code': '>>> postban_rates.num_rows == 44\nTrue', 'hidden': False, 'locked': False,
                                    "failure_message":"""The shape of `preban_rates` table is incorrect. Expected 44 rows in table."""},
                                   {'code': '>>> np.all(postban_rates.column("Death Penalty") == False)\nTrue', 'hidden': False, 'locked': False,
                                    "failure_message":"""Incorrect: Ensure that the `postban_rates` table only contain death penalties. Check the instructions again."""},
                                   {'code': '>>> np.all(postban_rates.column("Year") == 1973)\nTrue', 'hidden': False, 'locked': False,
                                     "failure_message":"""It seems that you have included the wrong year in `postban_rates`. Check the instructions again."""},
                                   {'code': '>>> all(elem in postban_rates.column("State") for elem in preban_rates.column("State"))\nTrue', 'hidden': False, 'locked': False,
                                    "failure_message":""""The provided answer for ``postban_rates`` is incorrect.""",
                                    "success_message":"""All answers provided are correct!"""}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
